const BIOMES = ["WATER", "BEACH", "PLAIN", "MOUNTAIN"];

const ANIMALS = ["FISH", "DEER", "NONE"];
const MATERIAL_RICHNESS = ["GOLD", "COPPER", "IRON", "NONE"];
const MOISTURE = ["DESERT", "FIELD", "FOREST", "NONE"];
